### ISSUE TITLE
How to use the Peckage

### ISSUE THREAD

**Issue by Bilal44559** [faizshukri/phpquran#7]
Hi, I am trying to use the peckage in my Laravel project and i am facing some problems while implementing and using it, i installed the peckage as told in the description, but i am facing difficulty in using it, Could you please guide me i mean how the peckage is working and flow of the peckage. and how to use it in the view, Thanks in advance.

**Comment by faizshukri** [comment]
Hi @Bilal44559,

Can you elaborate more what issue you're facing?

This is a simple example how you can do it from route after installing the package. (Laravel 10, PHP 8.2)

```php
<?php
// routes/web.php
use Illuminate\Support\Facades\Route;
use FaizShukri\Quran\Quran;

Route::get('/', function (Quran $quran) {
    dump($quran->translation('ar,en')->get('1:1-7'));
});
```

![image](https://github.com/faizshukri/phpquran/assets/1219518/8a3e4f2d-2271-4f39-bcab-ec377a6e627a)
